enum SearchResultType {
   DOCUMENT
   COLLECTION
}

enum SortDirection {
   ASC
   DESC
}

type SearchResultItem {
   type:       SearchResultType! @auth(rules: [{ allow: private }])
   document:   Document          @auth(rules: [{ allow: private }])
   collection: Collection        @auth(rules: [{ allow: private }])
   score:      Float             @auth(rules: [{ allow: private }])
}

type SearchResults {
   items:     [SearchResultItem!]! @auth(rules: [{ allow: private }])
   total:     Int!                 @auth(rules: [{ allow: private }])
   from:      Int!                 @auth(rules: [{ allow: private }])
   limit:     Int!                 @auth(rules: [{ allow: private }])
   nextToken: String               @auth(rules: [{ allow: private }])
}

extend type Query {
   search(
      query:         String!
      boxIds:        [ID!]
      field:         String
      sortField:     String
      sortDirection: SortDirection
      limit:         Int
      from:          Int
   ): SearchResults
        # @function(name: "searchRunner")
        # @auth(rules: [{ allow: private }])
        @aws_cognito_user_pools
}
