projects:
  hukdzen:
    schemaPath: amplify/backend/api/hukdzen/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/types/AmplifyTypes.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
