enum BoxRequestStatus {
   PENDING
   APPROVED
   DENIED
}

type BoxRequest @model @auth(rules: [{ allow: private,
                                       operations: [create, update, delete, read] }])
{
   id:            ID!
   requestedName: String!
   requestReason: String!
   status:        BoxRequestStatus!
   denialReason:  String                    #required if status = DENIED
   createdBy:     User              @hasOne #required validated in resolver
   approvedBy:    User              @hasOne #required if status = APPROVED
   createdBox:    Box             @hasOne #required if status = APPROVED
}

type BoxRequestList @aws_iam @aws_cognito_user_pools
{
   items:     [BoxRequest]
   nextToken: String
}

input BoxRequestFilterInput
{
   id:                        IDFilter
   requestedName:             StringFilter
   requestReason:             StringFilter
   status:                    ModelBoxRequestStatusInput
   denialReason:              StringFilter
   boxRequestCreatedById:     IDFilter
   boxRequestApprovedById:    IDFilter
   boxRequestCreatedBoxId:    IDFilter
   and:                       [BoxRequestFilterInput]
   or:                        [BoxRequestFilterInput]
   not:                       BoxRequestFilterInput
}

input BoxRequestInput
{
   id:            ID
   requestedName: String!
   requestReason: String!
   status:        BoxRequestStatus!
   denialReason:  String
   createdByUserId: ID!
   approvedByUserId: ID
   createdBoxId: ID
}

extend type Query {
   getBoxRequestDetailed(id: ID!): BoxRequest
      @aws_cognito_user_pools

   listBoxRequestDetailed(
      filter: BoxRequestFilterInput
      limit: Int
      nextToken: String
   ): BoxRequestList
      @aws_cognito_user_pools
}

extend type Mutation {
   createBoxRequestGuarded(input: BoxRequestInput!): BoxRequest
      @aws_cognito_user_pools

   updateBoxRequestGuarded(input: BoxRequestInput!): BoxRequest
      @aws_cognito_user_pools
}
