enum BoxRequestStatus {
   PENDING
   APPROVED
   DENIED
}

type BoxRequest @model @auth(rules: [{ allow: private,
                                       operations: [create, update, delete, read] }])
{
   id:            ID!
   requestedName: String!
   requestReason: String!
   status:        BoxRequestStatus!
   denialReason:  String                    #required if status = DENIED
   createdBy:     User              @hasOne #required validated in resolver
   approvedBy:    User              @hasOne #required if status = APPROVED
   createdBox:    Xbiis             @hasOne #required if status = APPROVED
}

type BoxRequestList
{
   items:     [BoxRequest]
   nextToken: String
}

input BoxRequestFilterInput
{
   id:            IDFilter
   requestedName: StringFilter
   requestReason: StringFilter
   denialReason:  StringFilter
   and:           [BoxRequestFilterInput]
   or:            [BoxRequestFilterInput]
   not:           BoxRequestFilterInput
}

input BoxRequestInput
{
   id:            ID
   requestedName: String!
   requestReason: String!
   status:        BoxRequestStatus!
   denialReason:  String
   createdByUserId: ID!
   approvedByUserId: ID
   createdBoxXbiisId: ID
}

extend type Query {
   getBoxRequestDetailed(id: ID!): BoxRequest
   listBoxRequestDetailed(
      filter: BoxRequestFilterInput
      limit: Int
      nextToken: String
   ): BoxRequestList
}

extend type Mutation {
   createBoxRequestGuarded(input: BoxRequestInput!): BoxRequest
   updateBoxRequestGuarded(input: BoxRequestInput!): BoxRequest
}
