import {useCallback, useState} from "react";
import { generateClient } from '@aws-amplify/api'

import { searchDocumentDetails } from '../../graphql/queries';
import { SearchDocumentDetailsQueryVariables } from "../../types/AmplifyTypes";

import { alertBarActions } from "../../AlertBar/AlertBarSlice";
import { buildWarningAlert } from "../../AlertBar/AlertBarTypes";
import { useAppDispatch } from "../../app/hooks";


const client = generateClient();


/**
 *  Checks if Document already exists
 *  *NOTE:* Code Originally generated by AmazonQ
 */
const useIfDocumentExists = () =>
{
   const [checking, setChecking] = useState(false);
   const dispatch = useAppDispatch();

   const checkExists = useCallback(async (docId: string, boxId: string,
                                          fileHash: string, fileKey: string) =>
   {
      setChecking(true);
      let exists = true; //assume exists unless successful
      try
      {
         console.log('Starting duplicate check...');
         const queryParams : SearchDocumentDetailsQueryVariables =
               {
                  filter: {
                     id: { ne: docId, },
                     documentDetailsBoxId: { eq: boxId },
                     or: [
                        { fileKey:  { eq: fileKey, } },
                        { fileHash: { eq: fileHash, } },
                     ]
                  }
               }

         const result =
               await client.graphql({ query: searchDocumentDetails,
                                      variables: queryParams, });
         /*
         const result = await Promise.race([
             client.graphql({ query: searchDocumentDetails, variables: queryParams }),
             new Promise((_, reject) => setTimeout(() => reject(new Error('Timeout')), 5000))
          ]);
          */

         console.log('Duplicate check completed'); // Add this
         exists = result.data.searchDocumentDetails.items.length > 0;
         if (exists)
         {
            dispatch(alertBarActions.DisplayAlertBox(buildWarningAlert('file exists.')));
         }
      }
      catch (error)
      {
         console.error('Error checking if document exists:', error);

         // If it's a GraphQL error, try to get more details
         // @ts-ignore
         if (error.errors)
         {  // @ts-ignore
            error.errors.forEach((err, index) => {
               console.error('Error', index, ':', err);
            });

            /*
             // assume data exists on error
             // prints items in case of a data error
             // @ts-ignore
             error.data.searchDocumentDetails.items.forEach((item, index) => {
             console.log(`Item ${index}:`,
             { id: item.id, fileKey: item.fileKey,
             keywords: item.keywords, keywordsType: typeof item.keywords,
             keywordsIsArray: Array.isArray(item.keywords) });
             });
             */
         }
      }
      finally
      {
         console.log('checkExists Callback finished.', exists);
         setChecking(false);
      }
      return exists;
   }, [dispatch]);

   return { checkExists, checking };
};

export default useIfDocumentExists;