//type TranslationMap = { [key: string]: string };

// noinspection JSNonASCIINames
/**
 *  Character Map with Alaskan Key to BC Orthography mapping
 *  @private
 */
const alaskanToBCMap= {
   /*
    *  IMPORTANT - ORDER MATTERS,
    *  ensure any keys are BEFORE matching values
    *  put the longer values before the shorter ones
    */
   'ee'  : 'ii',  'ai'  : 'ee',
   'uu'  : 'ü',   'oo'  : 'uu',  'oa'  : 'oo',
   "'ds" : "ts'", 'ds'  : 'dz',  "'d"  : "t'",
   "'kw" : "k'w", "'ky" : "k'y", "'k"  : "k'",
   "gg'" : "'g̱",  'gg'  : 'g̱',
   'ie'  : 'ay',
   'ck'  : 'x',
   'hl'  : 'ł',
   'sh'  : 's',
   "'b"  : "p'",
};

// noinspection JSNonASCIINames
/**
 *  Character Map with BC Key to Alaskan Orthography mapping
 *  @private
 */
const bCToAlaskanMap = {
   /*
    *  IMPORTANT - ORDER MATTERS,
    *  ensure any keys are BEFORE matching values
    *  put the longer values before the shorter ones
    */
   'ee'  : 'ai',  'ii'  : 'ee',
   'oo'  : 'oa',  'uu'  : 'oo',  'ü'   : 'uu',
   "ts'" : "'ds", "t'"  : "'d",
   "k'w" : "'kw", "k'y" : "'ky", "k'" : "'k",
   "ḵ"   : "gg",  "ḵ’"  : "'gg",
   'g̱'   : 'gg',
   'dz'  : 'ds',
   'ay'  : 'ie',
   'x'   : 'ck',
   'ł'   : 'hl',
   's'   : 'sh',
   "p'"  : "'b",
};

/**
 *   Class for Translating between Orthographies
 *   Based on a Skeleton Generated by Bing. (Chat GPT-4)
 */
class Translator
{

   alaskanToBC() { return alaskanToBCMap; }

   bCToAlaskan()  { return bCToAlaskanMap; }

   /**
    *   Translates the given text (assumed to be in Alaskan orthography) to BC Orthography.
    *   @param   {string} text - The text to be translated.
    *   @returns {string} The translated text.
    */
   translateToBC(text) { return this.#translate(text, alaskanToBCMap); }

   /**
    *   Translates the given text (assumed to be in BC Orthography) to Alaskan orthography.
    *   @param   {string} text - The text to be translated.
    *   @returns {string} The translated text.
    */
   translateToAlaskan(text) { return this.#translate(text, bCToAlaskanMap); }

   /**
    *   Translates the given text using the provided translation map.
    *   Private/Backend method to handle the translation logic.
    *   @param   {string} text - The text to be translated.
    *   @param   {Map} translationMap - The translation map to be used.
    *   @returns {string} The translated text.
    *   @private
    */
   #translate(text, translationMap)
   {
      if (!text || typeof text !== 'string') { return text || ''; }

      let translatedText = text;
      // TODO: fix translation issue, stop first one.
      for (const key in translationMap)
      {
         const value = translationMap[key];
         const regex = new RegExp(key, "gi");
         translatedText = translatedText.replace(regex, value);
      }
      /*
      //TODO: how do I do this?
      //loop through the text to translate 3 chars at a time,
      // compare to the map.
      for(let i = 0; i < text.length-3; i++)
      {
         const section = text.substring(i,i+4);
         if ( translationMap.includes(section) )
         {

         }
         else { translatedText += text.substring(i,i+1); }
      }
      */
      return translatedText;
   }
}

//export default Translator;
module.exports = Translator;

/* TEST && usage example
const Translator = new Translator();
const bcText = Translator.translateToBC("Your Alaskan text here");
const alaskanText = Translator.translateToAlaskan("Your BC text here");
// end TEST && usage example */