//type TranslationMap = { [key: string]: string };

/**
 *  Character Map with Alaskan Key to BC Orthography mapping
 *  @private
 */
const alaskanToBCMap= {
   /*
    *  IMPORTANT - ORDER MATTERS,
    *  ensure any keys are BEFORE matching values
    *  put the longer values before the shorter ones
    */
   "'kw" : "k'w", "'ky" : "k'y", "gg'" : "'g̱",
   "'ds" : "ts'", "'d"  : "t'",
   "'k"  : "k'",  "'b"  : "p'",
   'ee'  : 'ii',  'ai'  : 'ee',
   'uu'  : 'ü',   'oo'  : 'uu',  'oa'  : 'oo',
   'ds'  : 'dz',
   'ie'  : 'ay',
   //'a'   : 'a̱',
   'gg'  : 'g̱',
   'ck'  : 'x',
   'hl'  : 'ł',
   'sh'  : 's',
};

// noinspection JSNonASCIINames
/**
 *  Character Map with BC Key to Alaskan Orthography mapping
 *  @private
 */
const bCToAlaskanMap = {
   /*
    *  IMPORTANT - ORDER MATTERS,
    *  ensure any keys are BEFORE matching values
    *  put the longer values before the shorter ones
    */
   "k'w" : "'kw", "k'y" : "'ky", "ḵ'"  : "'gg",
   "ts'" : "'ds", "t'"  : "'d",
   "k'"  : "'k",  "p'"  : "'b",
   'ee'  : 'ai',  'ii'  : 'ee',
   'oo'  : 'oa',  'uu'  : 'oo',  'ü'   : 'uu',
   'dz'  : 'ds',
   'ay'  : 'ie',  'a̱'   : 'a',
   'g̱'   : 'gg',
   "ḵ"   : "gg",
   'x'   : 'ck',
   'ł'   : 'hl',
   's'   : 'sh',
};

const CaseType = {
   ALL_UPPER: 'ALL_UPPER',
   ALL_LOWER: 'ALL_LOWER',
   MIXED:     'MIXED',
};

/**
 *   Class for Translating between Orthographies
 *   Based on a Skeleton Generated by Bing. (Chat GPT-4)
 */
class Translator
{

   alaskanToBC() { return alaskanToBCMap; }

   bCToAlaskan()  { return bCToAlaskanMap; }

   /**
    *   Translates the given text (assumed to be in Alaskan orthography) to BC Orthography.
    *   @param   {string} text - The text to be translated.
    *   @returns {string} The translated text.
    */
   translateToBC(text) { return this.#translate(text, alaskanToBCMap); }

   /**
    *   Translates the given text (assumed to be in BC Orthography) to Alaskan orthography.
    *   @param   {string} text - The text to be translated.
    *   @returns {string} The translated text.
    */
   translateToAlaskan(text) { return this.#translate(text, bCToAlaskanMap); }

   /**
    *   Translates the given text using the provided translation map.
    *   Private/Backend method to handle the translation logic.
    *   @param   {string} text - The text to be translated.
    *   @param   {Map} translationMap - The translation map to be used.
    *   @returns {string} The translated text.
    *   @private
    */
   #translate(text, translationMap)
   {
      if (!text || typeof text !== 'string') { return text || ''; }

      //determine case type for the original string
      const casing = text === text.toUpperCase() ? CaseType.ALL_UPPER
                                                 : text === text.toLowerCase() ?
                                                            CaseType.ALL_LOWER :
                                                            CaseType.MIXED;

      let result = '';
      let i = 0;
      
      while (i < text.length)
      {
         let matched = false;
         
         // Try to match patterns in map order (longest first due to hand-sorting)
         for (const key in translationMap)
         {
            const lowerText = text.toLowerCase();
            const lowerKey = key.toLowerCase();

            //console.log('text:', lowerText);
            //console.log('key:',  lowerKey);

            if (lowerText.substring(i, i + key.length) === lowerKey)
            {  // Preserve original case in the replacement, based on casing
               const originalSegment = text.substring(i, i + key.length);
               const replacement = this.#preserveCase(originalSegment,
                                                             translationMap[key],
                                                             casing);
               result += replacement;
               i += key.length;
               matched = true;
               //console.log('appending:', replacement);
               break;
            }
         }
         
         if (!matched)
         {
            result += text[i];
            i++;
            //console.log('string so far', result);
         }
      }

      //console.log('Translation Result:', result);
      return result;
   }
   
   /**
    * Preserves the case pattern of the original text in the replacement
    * @param {string} original - The original text segment
    * @param {string} replacement - The replacement text
    * @param caseType - The case type of the original text
    * @returns {string} The replacement with preserved case
    * @private
    */
   #preserveCase(original, replacement, caseType)
   {
      if ( caseType === CaseType.ALL_UPPER) { return replacement.toUpperCase(); }
      if ( caseType === CaseType.ALL_LOWER) { return replacement.toLowerCase(); }

      //console.log('preserveCase:', original, replacement);
      // All uppercase
      if (original === original.toUpperCase())
      {
         if ( original.length >= replacement.length )
         { return replacement.toUpperCase(); }
         //if ( original.length < replacement.length )
         //{ return this.#upperfirstLetter(replacement); }
         return this.#upperFirstLetter(replacement);
      }

      // All lowercase (probably, redundant, map should be lowercase already)
      if ( original === original.toLowerCase() )
      { return replacement.toLowerCase(); }
      
      // Title case (first char upper, rest lower) or single uppercase char
      if (original[0] === original[0].toUpperCase())
      { return this.#upperFirstLetter(replacement); }

      //console.log('replace:',      replacement);
      return replacement;
   }

   /** Regex to Find the first letter in a string. */
   static #FIND_FIRST_LETTER = /[\p{L}]/u;

   /**
    *   Capitalizes the first letter of the given text.
    *   Skips non letters like '
    *   @param   {string} text - The text to be capitalized.
    *   @returns {string} The capitalized text.
    *   @private
    */
   #upperFirstLetter(text)
   {
      return text.replace(Translator.#FIND_FIRST_LETTER,
                          match => match.toUpperCase());
   }
}

//export default Translator;
module.exports = Translator;

/* TEST && usage example
const Translator = new Translator();
const bcText = Translator.translateToBC("Your Alaskan text here");
const alaskanText = Translator.translateToAlaskan("Your BC text here");
// end TEST && usage example */