type Author implements Gyet @model @auth(rules: [{ allow: private,
                                                   operations: [create, update, delete, read] }])
{
   id:    ID!
   name:  String!
   clan:  Clan
   waa:   String
   email: AWSEmail
}

type AuthorList
{
   items:     [Author]
   nextToken: String
}

input AuthorFilterInput
{
   id:    IDFilter
   name:  StringFilter
   waa:   StringFilter
   and:   [AuthorFilterInput]
   or:    [AuthorFilterInput]
   not:   AuthorFilterInput
}

input AuthorInput
{
   id:    ID
   name:  String!
   clan:  Clan
   waa:   String
   email: AWSEmail
}

extend type Query {
   getAuthorDetailed(id: ID!): Author
   listAuthorDetailed(
      filter: AuthorFilterInput
      limit: Int
      nextToken: String
   ): AuthorList
}

extend type Mutation {
   createAuthorGuarded(input: AuthorInput!): Author
   updateAuthorGuarded(input: AuthorInput!): Author
}
