type Author implements Gyet @model @auth(rules: [{ allow: private,
                                                   operations: [create, update, delete, read] }])
{
   id:    ID!
   name:  String!
   clan:  Clan
   waa:   String
   email: AWSEmail
}

extend type Query {
   getAuthorDetailed(id: ID!): Author
   listAuthorDetailed(
      filter: ModelAuthorFilterInput
      limit: Int
      nextToken: String
   ): ModelAuthorConnection
}

extend type Mutation {
   createAuthorGuarded(input: CreateAuthorInput!): Author
   updateAuthorGuarded(input: UpdateAuthorInput!): Author
}
