type Author implements Gyet @model @auth(rules: [{ allow: private,
                                                   operations: [create, update, delete, read] }])
{
   id:    ID!
   name:  String!
   clan:  Clan
   waa:   String
   email: AWSEmail
}

type AuthorList @aws_iam @aws_cognito_user_pools
{
   items:     [Author]
   nextToken: String
}

input AuthorFilterInput
{
   id:    IDFilter
   name:  StringFilter
   clan:  ModelClanInput
   waa:   StringFilter
   email: StringFilter
   and:   [AuthorFilterInput]
   or:    [AuthorFilterInput]
   not:   AuthorFilterInput
}

input AuthorInput
{
   id:    ID
   name:  String!
   clan:  Clan
   waa:   String
   email: AWSEmail
}

extend type Query {
   getAuthorDetailed(id: ID!): Author
      @aws_cognito_user_pools

   listAuthorDetailed(
      filter: AuthorFilterInput
      limit: Int
      nextToken: String
   ): AuthorList
      @aws_cognito_user_pools
}

extend type Mutation {
   createAuthorGuarded(input: AuthorInput!): Author
      @aws_cognito_user_pools

   updateAuthorGuarded(input: AuthorInput!): Author
      @aws_cognito_user_pools
}
