enum OptOutReason {
   BOUNCE_HARD
   BOUNCE_SOFT
   COMPLAINT
   USER_CHOICE
}

type EmailPreferences {
   allOptOut:          Boolean
   boxRequestOptOut:   Boolean
   collaboratorOptOut: Boolean
   systemOptOut:       Boolean
   optOutReason:       OptOutReason
   optOutAt:           AWSDateTime
   softBounceCount:    Int
}

type User implements Gyet @model @auth(rules: [{ allow: private,
                                                 operations: [create, update, delete, read] }])
{
   id:               ID!
   name:             String!
   clan:             Clan
   waa:              String
   email:            AWSEmail!        @index(name: "byEmail", queryField: "getUserByEmail")
   isAdmin:          Boolean
   emailPreferences: EmailPreferences
}

type UserList
{
   items:     [User]
   nextToken: String
}

input UserFilterInput
{
   id:      IDFilter
   name:    StringFilter
   waa:     StringFilter
   isAdmin: BooleanFilter
   and:     [UserFilterInput]
   or:      [UserFilterInput]
   not:     UserFilterInput
}

input EmailPreferencesInput
{
   allOptOut:          Boolean
   boxRequestOptOut:   Boolean
   collaboratorOptOut: Boolean
   systemOptOut:       Boolean
   optOutReason:       OptOutReason
   optOutAt:           AWSDateTime
   softBounceCount:    Int
}

input UserInput
{
   id:               ID
   name:             String!
   clan:             Clan
   waa:              String
   email:            AWSEmail!
   isAdmin:          Boolean
   emailPreferences: EmailPreferencesInput
}

extend type Query {
   getUserDetailed(id: ID!): User
   listUserDetailed(
      filter: UserFilterInput
      limit: Int
      nextToken: String
   ): UserList
}

extend type Mutation {
   createUserGuarded(input: UserInput!): User
   updateUserGuarded(input: UserInput!): User
}
