input CollectionInput
{
   id:                     ID
   eng:                    SummaryInput
   bc:                     SummaryInput
   ak:                     SummaryInput
   collectionOwnerUserId:  ID!
   boxXbiisId:             ID!
}

input CollectionItemInput
{
   id:                     ID
   collectionCollectionId: ID!
   documentDetailsId:      ID
   childCollectionId:      ID
   order:                  Int
}

input CollectionFilterInput
{
   id:                           IDFilter
   eng:                          SummaryFilterInput
   bc:                           SummaryFilterInput
   ak:                           SummaryFilterInput
   created:                      DateTimeFilter
   updated:                      DateTimeFilter
   collectionBoxId:              IDFilter
   collectionContentOwnerUserId: IDFilter
   and:                          [CollectionFilterInput]
   or:                           [CollectionFilterInput]
   not:                          CollectionFilterInput
}

input CollectionItemFilterInput
{
   id:                              IDFilter
   collectionCollectionId:          IDFilter
   collectionItemDocumentId:        IDFilter
   collectionItemChildCollectionId: IDFilter
   order:                           IntFilter
   created:                         DateTimeFilter
   and:                             [CollectionItemFilterInput]
   or:                              [CollectionItemFilterInput]
   not:                             CollectionItemFilterInput
}
