enum BoxPurpose {
   USER    # Personal User box, created automatically
   GROUP   # Group / Shared / Requested boxes
   DEFAULT # Default Public box
}

type Xbiis @model @auth(rules: [{ allow: private,
                                  operations: [create, update, delete, read] }])
{
   id:          ID!
   name:        String!
   waa:         String
   owner:       User        @hasOne #required validated in resolver
   defaultRole: AccessLevel
   purpose:     BoxPurpose
   ownerUserId: ID          @index(name: "byOwner", queryField: "xbiisByOwner")
}

type XbiisList @aws_iam @aws_cognito_user_pools
{
   items:     [Xbiis]
   nextToken: String
}

input XbiisFilterInput
{
   id:            IDFilter
   name:          StringFilter
   waa:           StringFilter
   defaultRole:   ModelAccessLevelInput
   purpose:       ModelBoxPurposeInput
   ownerUserId:   IDFilter
   xbiisOwnerId:  IDFilter
   and:           [XbiisFilterInput]
   or:            [XbiisFilterInput]
   not:           XbiisFilterInput
}

input XbiisInput
{
   id:          ID
   name:        String!
   waa:         String
   defaultRole: AccessLevel
   purpose:     BoxPurpose
   ownerUserId: ID!
}

extend type Query {
   getXbiisDetailed(id: ID!): Xbiis
      @aws_cognito_user_pools

   listXbiisDetailed(
      filter: XbiisFilterInput
      limit: Int
      nextToken: String
   ): XbiisList
      @aws_cognito_user_pools
}

extend type Mutation {
   createXbiisGuarded(input: XbiisInput!): Xbiis
      @aws_cognito_user_pools

   updateXbiisGuarded(input: XbiisInput!): Xbiis
      @aws_cognito_user_pools
}
