enum BoxPurpose {
   USER    # Personal User box, created automatically
   GROUP   # Group / Shared / Requested boxes
   DEFAULT # Default Public box
}

type Box @model @auth(rules: [{ allow: private,
                                  operations: [create, update, delete, read] }])
{
   id:          ID!
   name:        String!
   waa:         String
   owner:       User        @hasOne #required validated in resolver
   defaultRole: AccessLevel!
   purpose:     BoxPurpose!
   ownerUserId: ID!         @index(name: "byOwner", queryField: "boxesByOwner")
}

type BoxList @aws_iam @aws_cognito_user_pools
{
   items:     [Box]
   nextToken: String
}

input BoxFilterInput
{
   id:            IDFilter
   name:          StringFilter
   waa:           StringFilter
   defaultRole:   ModelAccessLevelInput
   purpose:       ModelBoxPurposeInput
   ownerUserId:   IDFilter
   boxOwnerId:    IDFilter
   and:           [BoxFilterInput]
   or:            [BoxFilterInput]
   not:           BoxFilterInput
}

input BoxInput
{
   id:          ID
   name:        String!
   waa:         String
   defaultRole: AccessLevel
   purpose:     BoxPurpose
   ownerUserId: ID!
}

extend type Query {
   getBoxDetailed(id: ID!): Box
      @aws_cognito_user_pools

   listBoxDetailed(
      filter: BoxFilterInput
      limit: Int
      nextToken: String
   ): BoxList
      @aws_cognito_user_pools
}

extend type Mutation {
   createBoxGuarded(input: BoxInput!): Box
      @aws_cognito_user_pools

   updateBoxGuarded(input: BoxInput!): Box
      @aws_cognito_user_pools
}
