type BoxUser @model @auth(rules: [{ allow: private,
                                    operations: [create, update, delete, read] },
                                  { allow: private, provider: iam,
                                    operations: [read] }])
{
   id:         ID!
   user:       User         @hasOne #required validated in resolver
   box:        Xbiis        @hasOne #required validated in resolver
   role:       AccessLevel!
   userUserId: ID!          @index(name: "byUser", queryField: "boxUsersByUser")
}

type BoxUserList @aws_iam @aws_cognito_user_pools
{
   items:     [BoxUser]
   nextToken: String
}

input BoxUserFilterInput
{
   id:              IDFilter
   role:            ModelAccessLevelInput
   userUserId:      IDFilter
   boxUserBoxId:    IDFilter
   boxUserUserId:   IDFilter
   and:             [BoxUserFilterInput]
   or:              [BoxUserFilterInput]
   not:             BoxUserFilterInput
}

input BoxUserInput
{
   id:     ID
   role:   AccessLevel!
   userId: ID!
   boxId:  ID!
}

extend type Query {
   getBoxUserDetailed(id: ID!): BoxUser
      @aws_cognito_user_pools
   listBoxUserDetailed(
      filter: BoxUserFilterInput
      limit: Int
      nextToken: String
   ): BoxUserList
      @aws_cognito_user_pools
}

extend type Mutation {
   createBoxUserGuarded(input: BoxUserInput!): BoxUser
      @aws_cognito_user_pools
   updateBoxUserGuarded(input: BoxUserInput!): BoxUser
      @aws_cognito_user_pools
}
