input DocumentDetailsInput
{
   id:                ID
   eng_title:         String!
   eng_description:   String!
   fileKey:           String!
   fileHash:          String
   type:              String
   version:           Float!
   bc_title:          String!
   bc_description:    String!
   ak_title:          String!
   ak_description:    String!
   keywords:          [String]
   boxXbiisId:        ID!
   docOwnerUserId:    ID!
   authorId:          ID!
}

input DocumentDetailsFilterInput
{
   id:                IDFilter
   eng_title:         StringFilter
   eng_description:   StringFilter
   fileKey:           StringFilter
   fileHash:          StringFilter
   created:           DateTimeFilter
   updated:           DateTimeFilter
   type:              StringFilter
   version:           FloatFilter
   bc_title:          StringFilter
   bc_description:    StringFilter
   ak_title:          StringFilter
   ak_description:    StringFilter
   boxXbiisId:        IDFilter
   docOwnerUserId:    IDFilter
   and:               [DocumentDetailsFilterInput]
   or:                [DocumentDetailsFilterInput]
   not:               DocumentDetailsFilterInput
}
